export type CrossLink = {
  lessonId: string;
  lessonPath: string;
  lessonTitle: string;
  lessonLevel: 1 | 2 | 3;
  hubPath: string;
  hubAnchor?: string;
  hubTitle: string;
  sectionTitle: string;
  contextInLesson: string;
  contextInHub: string;
};

export const CROSSLINKS: CrossLink[] = [
  // ── Урок 1.1: Что такое обучение с подкреплением? ──
  {
    lessonId: "1-1",
    lessonPath: "/courses/1-1",
    lessonTitle: "Что такое обучение с подкреплением?",
    lessonLevel: 1,
    hubPath: "/deep-rl",
    hubAnchor: "foundations",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Основы Deep RL",
    contextInLesson: "Базовые концепции RL — агент, среда, награда, политика",
    contextInHub: "Фундамент, необходимый для понимания всех алгоритмов (Урок 1.1)",
  },
  {
    lessonId: "1-1",
    lessonPath: "/courses/1-1",
    lessonTitle: "Что такое обучение с подкреплением?",
    lessonLevel: 1,
    hubPath: "/math-rl/module-3",
    hubTitle: "Математика RL — Вероятности",
    sectionTitle: "Теория вероятностей для RL",
    contextInLesson: "Вероятностные основы переходов и наград",
    contextInHub: "Математика за MDP и стохастическими политиками (Урок 1.1)",
  },
  {
    lessonId: "1-1",
    lessonPath: "/courses/1-1",
    lessonTitle: "Что такое обучение с подкреплением?",
    lessonLevel: 1,
    hubPath: "/math-rl/module-5",
    hubTitle: "Математика RL — Q-Learning",
    sectionTitle: "Основы Q-функции",
    contextInLesson: "Введение в value-функции и Q-значения",
    contextInHub: "Формальное определение Q-функции, используемой в Уроке 1.1",
  },
  {
    lessonId: "1-1",
    lessonPath: "/courses/1-1",
    lessonTitle: "Что такое обучение с подкреплением?",
    lessonLevel: 1,
    hubPath: "/algorithms/dqn",
    hubTitle: "DQN — Deep Q-Network",
    sectionTitle: "Алгоритм DQN",
    contextInLesson: "Первое знакомство с deep value-based методом",
    contextInHub: "Контекст: базовые понятия RL из Урока 1.1",
  },

  // ── Урок 1.2: Установка окружения ──
  {
    lessonId: "1-2",
    lessonPath: "/courses/1-2",
    lessonTitle: "Установка окружения: PyTorch + Unity ML-Agents",
    lessonLevel: 1,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "setup",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Установка и настройка PyTorch",
    contextInLesson: "Установка PyTorch и проверка GPU",
    contextInHub: "Справка по установке, используемая в Уроке 1.2",
  },
  {
    lessonId: "1-2",
    lessonPath: "/courses/1-2",
    lessonTitle: "Установка окружения: PyTorch + Unity ML-Agents",
    lessonLevel: 1,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "tensors",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Тензоры (torch.Tensor)",
    contextInLesson: "Основы работы с тензорами — базовые операции",
    contextInHub: "Справка по тензорам для практики в Уроке 1.2",
  },
  {
    lessonId: "1-2",
    lessonPath: "/courses/1-2",
    lessonTitle: "Установка окружения: PyTorch + Unity ML-Agents",
    lessonLevel: 1,
    hubPath: "/unity-ml-agents",
    hubAnchor: "installation",
    hubTitle: "Unity ML-Agents",
    sectionTitle: "Установка ML-Agents",
    contextInLesson: "Параллельная настройка Unity ML-Agents",
    contextInHub: "Подробности установки для Урока 1.2",
  },

  // ── Урок 1.3: CartPole ──
  {
    lessonId: "1-3",
    lessonPath: "/courses/1-3",
    lessonTitle: "CartPole — твой первый RL-агент",
    lessonLevel: 1,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "nn",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Нейронные сети (torch.nn)",
    contextInLesson: "Построение простой нейросети для CartPole",
    contextInHub: "nn.Module в действии — пример из Урока 1.3",
  },
  {
    lessonId: "1-3",
    lessonPath: "/courses/1-3",
    lessonTitle: "CartPole — твой первый RL-агент",
    lessonLevel: 1,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "training",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Цикл обучения",
    contextInLesson: "Цикл обучения: forward → loss → backward → step",
    contextInHub: "Практический цикл обучения из Урока 1.3",
  },
  {
    lessonId: "1-3",
    lessonPath: "/courses/1-3",
    lessonTitle: "CartPole — твой первый RL-агент",
    lessonLevel: 1,
    hubPath: "/algorithms/dqn",
    hubTitle: "DQN — Deep Q-Network",
    sectionTitle: "Алгоритм DQN",
    contextInLesson: "CartPole как базовая среда для проверки DQN",
    contextInHub: "Среда CartPole для первых экспериментов (Урок 1.3)",
  },
  {
    lessonId: "1-3",
    lessonPath: "/courses/1-3",
    lessonTitle: "CartPole — твой первый RL-агент",
    lessonLevel: 1,
    hubPath: "/pytorch",
    hubTitle: "PyTorch Hub",
    sectionTitle: "PyTorch для RL",
    contextInLesson: "Полный справочник PyTorch для RL-задач",
    contextInHub: "Основы PyTorch, применяемые в Уроке 1.3",
  },

  // ── Урок 1.4: DQN с нуля ──
  {
    lessonId: "1-4",
    lessonPath: "/courses/1-4",
    lessonTitle: "DQN с нуля на PyTorch",
    lessonLevel: 1,
    hubPath: "/algorithms/dqn",
    hubTitle: "DQN — Deep Q-Network",
    sectionTitle: "Алгоритм DQN",
    contextInLesson: "Полная реализация DQN: replay buffer, target network",
    contextInHub: "Детальная реализация DQN из Урока 1.4",
  },
  {
    lessonId: "1-4",
    lessonPath: "/courses/1-4",
    lessonTitle: "DQN с нуля на PyTorch",
    lessonLevel: 1,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "nn",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Нейронные сети (torch.nn)",
    contextInLesson: "Архитектура Q-сети на nn.Module",
    contextInHub: "Пример архитектуры Q-сети из Урока 1.4",
  },
  {
    lessonId: "1-4",
    lessonPath: "/courses/1-4",
    lessonTitle: "DQN с нуля на PyTorch",
    lessonLevel: 1,
    hubPath: "/math-rl/module-5",
    hubTitle: "Математика RL — Q-Learning",
    sectionTitle: "Уравнение Беллмана",
    contextInLesson: "Математическая основа DQN — уравнение Беллмана",
    contextInHub: "Формула Беллмана в коде DQN (Урок 1.4)",
  },
  {
    lessonId: "1-4",
    lessonPath: "/courses/1-4",
    lessonTitle: "DQN с нуля на PyTorch",
    lessonLevel: 1,
    hubPath: "/math-rl/module-4",
    hubTitle: "Математика RL — Оптимизация",
    sectionTitle: "Градиентная оптимизация",
    contextInLesson: "Оптимизация Q-сети через SGD / Adam",
    contextInHub: "Оптимизация в контексте DQN (Урок 1.4)",
  },
  {
    lessonId: "1-4",
    lessonPath: "/courses/1-4",
    lessonTitle: "DQN с нуля на PyTorch",
    lessonLevel: 1,
    hubPath: "/deep-rl",
    hubAnchor: "algorithms",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Ключевые алгоритмы",
    contextInLesson: "DQN в контексте других Deep RL алгоритмов",
    contextInHub: "DQN — первый deep-метод, реализуемый в Уроке 1.4",
  },

  // ── Проект 1: Балансировка шеста ──
  {
    lessonId: "project-1",
    lessonPath: "/courses/project-1",
    lessonTitle: "Проект: Балансировка шеста",
    lessonLevel: 1,
    hubPath: "/unity-projects/ball-balance",
    hubTitle: "Проект Ball Balance",
    sectionTitle: "Балансировка в 3D",
    contextInLesson: "Аналогичная задача балансировки в 3D Unity-среде",
    contextInHub: "Родственный проект: CartPole → Ball Balance (Проект 1)",
  },
  {
    lessonId: "project-1",
    lessonPath: "/courses/project-1",
    lessonTitle: "Проект: Балансировка шеста",
    lessonLevel: 1,
    hubPath: "/algorithms/dqn",
    hubTitle: "DQN — Deep Q-Network",
    sectionTitle: "Алгоритм DQN",
    contextInLesson: "Применение DQN для задачи балансировки",
    contextInHub: "Практическое применение DQN в Проекте 1",
  },
  {
    lessonId: "project-1",
    lessonPath: "/courses/project-1",
    lessonTitle: "Проект: Балансировка шеста",
    lessonLevel: 1,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "saving",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Сохранение моделей",
    contextInLesson: "Сохранение обученной модели (state_dict)",
    contextInHub: "Сохранение модели на практике (Проект 1)",
  },

  // ── Урок 2.1: Policy Gradient ──
  {
    lessonId: "2-1",
    lessonPath: "/courses/2-1",
    lessonTitle: "Policy Gradient и теорема градиента",
    lessonLevel: 2,
    hubPath: "/deep-rl",
    hubAnchor: "algorithms",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Ключевые алгоритмы",
    contextInLesson: "Policy Gradient как альтернатива value-based методам",
    contextInHub: "Теорема градиента политики — основа Урока 2.1",
  },
  {
    lessonId: "2-1",
    lessonPath: "/courses/2-1",
    lessonTitle: "Policy Gradient и теорема градиента",
    lessonLevel: 2,
    hubPath: "/math-rl/module-3",
    hubTitle: "Математика RL — Вероятности",
    sectionTitle: "Теория вероятностей для RL",
    contextInLesson: "Логарифмические производные и REINFORCE",
    contextInHub: "Вероятностные основы градиента политики (Урок 2.1)",
  },
  {
    lessonId: "2-1",
    lessonPath: "/courses/2-1",
    lessonTitle: "Policy Gradient и теорема градиента",
    lessonLevel: 2,
    hubPath: "/math-rl/module-4",
    hubTitle: "Математика RL — Оптимизация",
    sectionTitle: "Градиентная оптимизация",
    contextInLesson: "Стохастический градиентный подъём для политики",
    contextInHub: "Оптимизация политики в Уроке 2.1",
  },
  {
    lessonId: "2-1",
    lessonPath: "/courses/2-1",
    lessonTitle: "Policy Gradient и теорема градиента",
    lessonLevel: 2,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "autograd",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Автоматическое дифференцирование",
    contextInLesson: "Autograd для вычисления градиента политики",
    contextInHub: "Autograd в контексте REINFORCE (Урок 2.1)",
  },

  // ── Урок 2.2: PPO ──
  {
    lessonId: "2-2",
    lessonPath: "/courses/2-2",
    lessonTitle: "PPO — реализация с нуля",
    lessonLevel: 2,
    hubPath: "/algorithms/ppo",
    hubTitle: "PPO — Proximal Policy Optimization",
    sectionTitle: "Алгоритм PPO",
    contextInLesson: "Clipped objective, GAE, mini-batch обновления",
    contextInHub: "Полная реализация PPO из Урока 2.2",
  },
  {
    lessonId: "2-2",
    lessonPath: "/courses/2-2",
    lessonTitle: "PPO — реализация с нуля",
    lessonLevel: 2,
    hubPath: "/math-rl/module-5",
    hubTitle: "Математика RL — Q-Learning",
    sectionTitle: "Advantage и GAE",
    contextInLesson: "Generalized Advantage Estimation в PPO",
    contextInHub: "Формула GAE, применяемая в Уроке 2.2",
  },
  {
    lessonId: "2-2",
    lessonPath: "/courses/2-2",
    lessonTitle: "PPO — реализация с нуля",
    lessonLevel: 2,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "nn",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Нейронные сети (torch.nn)",
    contextInLesson: "Архитектура Actor и Critic сетей",
    contextInHub: "Actor-Critic архитектура из Урока 2.2",
  },
  {
    lessonId: "2-2",
    lessonPath: "/courses/2-2",
    lessonTitle: "PPO — реализация с нуля",
    lessonLevel: 2,
    hubPath: "/unity-ml-agents",
    hubAnchor: "training",
    hubTitle: "Unity ML-Agents",
    sectionTitle: "Обучение агентов",
    contextInLesson: "Запуск PPO-обучения в Unity ML-Agents",
    contextInHub: "PPO-тренировка из Урока 2.2",
  },
  {
    lessonId: "2-2",
    lessonPath: "/courses/2-2",
    lessonTitle: "PPO — реализация с нуля",
    lessonLevel: 2,
    hubPath: "/deep-rl",
    hubAnchor: "algorithms",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Ключевые алгоритмы",
    contextInLesson: "PPO в семействе policy gradient алгоритмов",
    contextInHub: "PPO — ключевой алгоритм Урока 2.2",
  },

  // ── Урок 2.3: Непрерывные действия ──
  {
    lessonId: "2-3",
    lessonPath: "/courses/2-3",
    lessonTitle: "Непрерывные действия и Actor-Critic",
    lessonLevel: 2,
    hubPath: "/deep-rl",
    hubAnchor: "algorithms",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Ключевые алгоритмы",
    contextInLesson: "Actor-Critic для непрерывного пространства действий",
    contextInHub: "Actor-Critic архитектура из Урока 2.3",
  },
  {
    lessonId: "2-3",
    lessonPath: "/courses/2-3",
    lessonTitle: "Непрерывные действия и Actor-Critic",
    lessonLevel: 2,
    hubPath: "/unity-ml-agents",
    hubAnchor: "neural-networks",
    hubTitle: "Unity ML-Agents",
    sectionTitle: "Нейросети в ML-Agents",
    contextInLesson: "Настройка continuous actions в ML-Agents",
    contextInHub: "Непрерывные действия на практике (Урок 2.3)",
  },
  {
    lessonId: "2-3",
    lessonPath: "/courses/2-3",
    lessonTitle: "Непрерывные действия и Actor-Critic",
    lessonLevel: 2,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "nn",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Нейронные сети (torch.nn)",
    contextInLesson: "Gaussian Policy через nn.Module",
    contextInHub: "Gaussian Policy для непрерывных действий (Урок 2.3)",
  },
  {
    lessonId: "2-3",
    lessonPath: "/courses/2-3",
    lessonTitle: "Непрерывные действия и Actor-Critic",
    lessonLevel: 2,
    hubPath: "/algorithms/ppo",
    hubTitle: "PPO — Proximal Policy Optimization",
    sectionTitle: "PPO с непрерывными действиями",
    contextInLesson: "Адаптация PPO для continuous action space",
    contextInHub: "Continuous PPO из Урока 2.3",
  },

  // ── Урок 2.4: Reward Shaping ──
  {
    lessonId: "2-4",
    lessonPath: "/courses/2-4",
    lessonTitle: "Reward Shaping",
    lessonLevel: 2,
    hubPath: "/deep-rl",
    hubAnchor: "practice",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Практическое применение",
    contextInLesson: "Проектирование функции вознаграждения",
    contextInHub: "Reward shaping — практика из Урока 2.4",
  },
  {
    lessonId: "2-4",
    lessonPath: "/courses/2-4",
    lessonTitle: "Reward Shaping",
    lessonLevel: 2,
    hubPath: "/advanced",
    hubTitle: "Продвинутые темы",
    sectionTitle: "Продвинутые техники RL",
    contextInLesson: "Curriculum + reward shaping для сложных задач",
    contextInHub: "Reward shaping как продвинутая техника (Урок 2.4)",
  },
  {
    lessonId: "2-4",
    lessonPath: "/courses/2-4",
    lessonTitle: "Reward Shaping",
    lessonLevel: 2,
    hubPath: "/unity-ml-agents",
    hubAnchor: "training",
    hubTitle: "Unity ML-Agents",
    sectionTitle: "Обучение агентов",
    contextInLesson: "Настройка наград в Unity-средах",
    contextInHub: "Настройка reward в ML-Agents (Урок 2.4)",
  },
  {
    lessonId: "2-4",
    lessonPath: "/courses/2-4",
    lessonTitle: "Reward Shaping",
    lessonLevel: 2,
    hubPath: "/math-rl/module-5",
    hubTitle: "Математика RL — Q-Learning",
    sectionTitle: "Potential-based shaping",
    contextInLesson: "Математическое обоснование reward shaping",
    contextInHub: "Теория potential-based shaping (Урок 2.4)",
  },

  // ── Урок 2.5: Параллельные среды ──
  {
    lessonId: "2-5",
    lessonPath: "/courses/2-5",
    lessonTitle: "Параллельные среды",
    lessonLevel: 2,
    hubPath: "/unity-ml-agents",
    hubAnchor: "training",
    hubTitle: "Unity ML-Agents",
    sectionTitle: "Обучение агентов",
    contextInLesson: "Запуск множества экземпляров среды в ML-Agents",
    contextInHub: "Параллелизм для ускорения обучения (Урок 2.5)",
  },
  {
    lessonId: "2-5",
    lessonPath: "/courses/2-5",
    lessonTitle: "Параллельные среды",
    lessonLevel: 2,
    hubPath: "/deep-rl",
    hubAnchor: "practice",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Практическое применение",
    contextInLesson: "Масштабирование обучения через параллельные среды",
    contextInHub: "Параллельные среды на практике (Урок 2.5)",
  },

  // ── Урок 2.6: TensorBoard и W&B ──
  {
    lessonId: "2-6",
    lessonPath: "/courses/2-6",
    lessonTitle: "TensorBoard и W&B",
    lessonLevel: 2,
    hubPath: "/unity-ml-agents",
    hubAnchor: "training",
    hubTitle: "Unity ML-Agents",
    sectionTitle: "Обучение агентов",
    contextInLesson: "Мониторинг обучения ML-Agents через TensorBoard",
    contextInHub: "Интеграция TensorBoard с ML-Agents (Урок 2.6)",
  },
  {
    lessonId: "2-6",
    lessonPath: "/courses/2-6",
    lessonTitle: "TensorBoard и W&B",
    lessonLevel: 2,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "saving",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Сохранение моделей",
    contextInLesson: "Логирование чекпоинтов и метрик",
    contextInHub: "Сохранение + логирование из Урока 2.6",
  },
  {
    lessonId: "2-6",
    lessonPath: "/courses/2-6",
    lessonTitle: "TensorBoard и W&B",
    lessonLevel: 2,
    hubPath: "/deep-rl",
    hubAnchor: "practice",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Практическое применение",
    contextInLesson: "Мониторинг экспериментов Deep RL",
    contextInHub: "Визуализация обучения из Урока 2.6",
  },

  // ── Проект 2: 3D-охотник ──
  {
    lessonId: "project-2",
    lessonPath: "/courses/project-2",
    lessonTitle: "Проект: 3D-охотник",
    lessonLevel: 2,
    hubPath: "/unity-projects",
    hubTitle: "Проекты Unity",
    sectionTitle: "Все Unity-проекты",
    contextInLesson: "FoodCollector как флагманский 3D-проект",
    contextInHub: "Проект FoodCollector из Этапа 2",
  },
  {
    lessonId: "project-2",
    lessonPath: "/courses/project-2",
    lessonTitle: "Проект: 3D-охотник",
    lessonLevel: 2,
    hubPath: "/unity-ml-agents",
    hubAnchor: "neural-networks",
    hubTitle: "Unity ML-Agents",
    sectionTitle: "Нейросети в ML-Agents",
    contextInLesson: "Настройка нейросети для FoodCollector",
    contextInHub: "Конфигурация сети для 3D-охотника (Проект 2)",
  },
  {
    lessonId: "project-2",
    lessonPath: "/courses/project-2",
    lessonTitle: "Проект: 3D-охотник",
    lessonLevel: 2,
    hubPath: "/algorithms/ppo",
    hubTitle: "PPO — Proximal Policy Optimization",
    sectionTitle: "PPO для FoodCollector",
    contextInLesson: "Применение PPO в проекте FoodCollector",
    contextInHub: "PPO на практике — Проект 2",
  },

  // ── Проект 3: Гоночный агент ──
  {
    lessonId: "project-3",
    lessonPath: "/courses/project-3",
    lessonTitle: "Проект: Гоночный агент",
    lessonLevel: 2,
    hubPath: "/unity-projects/racing",
    hubTitle: "Проект Racing Car",
    sectionTitle: "Гоночный агент",
    contextInLesson: "Обучение агента управлению гоночным автомобилем",
    contextInHub: "Полный проект гоночного агента (Проект 3)",
  },
  {
    lessonId: "project-3",
    lessonPath: "/courses/project-3",
    lessonTitle: "Проект: Гоночный агент",
    lessonLevel: 2,
    hubPath: "/algorithms/ppo",
    hubTitle: "PPO — Proximal Policy Optimization",
    sectionTitle: "PPO для Racing",
    contextInLesson: "PPO с continuous actions для гонок",
    contextInHub: "PPO в задаче вождения (Проект 3)",
  },
  {
    lessonId: "project-3",
    lessonPath: "/courses/project-3",
    lessonTitle: "Проект: Гоночный агент",
    lessonLevel: 2,
    hubPath: "/deep-rl",
    hubAnchor: "algorithms",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Ключевые алгоритмы",
    contextInLesson: "Выбор алгоритма для задачи вождения",
    contextInHub: "Алгоритмы для continuous control (Проект 3)",
  },

  // ── Урок 3.1: SAC ──
  {
    lessonId: "3-1",
    lessonPath: "/courses/3-1",
    lessonTitle: "SAC — Soft Actor-Critic",
    lessonLevel: 3,
    hubPath: "/algorithms/sac",
    hubTitle: "SAC — Soft Actor-Critic",
    sectionTitle: "Алгоритм SAC",
    contextInLesson: "Энтропийная регуляризация и двойной Q-критик",
    contextInHub: "Полная теория SAC из Урока 3.1",
  },
  {
    lessonId: "3-1",
    lessonPath: "/courses/3-1",
    lessonTitle: "SAC — Soft Actor-Critic",
    lessonLevel: 3,
    hubPath: "/math-rl/module-5",
    hubTitle: "Математика RL — Q-Learning",
    sectionTitle: "Энтропийный бонус",
    contextInLesson: "Математика soft value функций",
    contextInHub: "Энтропийная формула для SAC (Урок 3.1)",
  },
  {
    lessonId: "3-1",
    lessonPath: "/courses/3-1",
    lessonTitle: "SAC — Soft Actor-Critic",
    lessonLevel: 3,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "nn",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Нейронные сети (torch.nn)",
    contextInLesson: "Двойной Q-критик на nn.Module",
    contextInHub: "Архитектура двойного Q-критика (Урок 3.1)",
  },
  {
    lessonId: "3-1",
    lessonPath: "/courses/3-1",
    lessonTitle: "SAC — Soft Actor-Critic",
    lessonLevel: 3,
    hubPath: "/deep-rl",
    hubAnchor: "algorithms",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Ключевые алгоритмы",
    contextInLesson: "SAC в контексте off-policy методов",
    contextInHub: "SAC — off-policy алгоритм Урока 3.1",
  },

  // ── Урок 3.2: MA-POCA и Self-Play ──
  {
    lessonId: "3-2",
    lessonPath: "/courses/3-2",
    lessonTitle: "MA-POCA и Self-Play",
    lessonLevel: 3,
    hubPath: "/advanced",
    hubTitle: "Продвинутые темы",
    sectionTitle: "Multi-Agent RL",
    contextInLesson: "Мультиагентное обучение через MA-POCA",
    contextInHub: "MA-POCA и self-play из Урока 3.2",
  },
  {
    lessonId: "3-2",
    lessonPath: "/courses/3-2",
    lessonTitle: "MA-POCA и Self-Play",
    lessonLevel: 3,
    hubPath: "/unity-ml-agents",
    hubAnchor: "training",
    hubTitle: "Unity ML-Agents",
    sectionTitle: "Обучение агентов",
    contextInLesson: "Настройка self-play в ML-Agents",
    contextInHub: "Self-play тренировка из Урока 3.2",
  },
  {
    lessonId: "3-2",
    lessonPath: "/courses/3-2",
    lessonTitle: "MA-POCA и Self-Play",
    lessonLevel: 3,
    hubPath: "/unity-projects/soccer",
    hubTitle: "Проект Soccer",
    sectionTitle: "Командный футбол",
    contextInLesson: "Soccer как среда для multi-agent обучения",
    contextInHub: "Мультиагентная среда Soccer (Урок 3.2)",
  },
  {
    lessonId: "3-2",
    lessonPath: "/courses/3-2",
    lessonTitle: "MA-POCA и Self-Play",
    lessonLevel: 3,
    hubPath: "/deep-rl",
    hubAnchor: "algorithms",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Ключевые алгоритмы",
    contextInLesson: "Multi-Agent RL в семействе Deep RL",
    contextInHub: "Мультиагентные алгоритмы (Урок 3.2)",
  },

  // ── Урок 3.3: Curriculum Learning ──
  {
    lessonId: "3-3",
    lessonPath: "/courses/3-3",
    lessonTitle: "Curriculum Learning",
    lessonLevel: 3,
    hubPath: "/advanced",
    hubTitle: "Продвинутые темы",
    sectionTitle: "Curriculum Learning",
    contextInLesson: "Постепенное усложнение задач для агента",
    contextInHub: "Теория и практика curriculum (Урок 3.3)",
  },
  {
    lessonId: "3-3",
    lessonPath: "/courses/3-3",
    lessonTitle: "Curriculum Learning",
    lessonLevel: 3,
    hubPath: "/unity-ml-agents",
    hubAnchor: "training",
    hubTitle: "Unity ML-Agents",
    sectionTitle: "Обучение агентов",
    contextInLesson: "Curriculum в YAML-конфигурации ML-Agents",
    contextInHub: "Настройка curriculum в ML-Agents (Урок 3.3)",
  },
  {
    lessonId: "3-3",
    lessonPath: "/courses/3-3",
    lessonTitle: "Curriculum Learning",
    lessonLevel: 3,
    hubPath: "/deep-rl",
    hubAnchor: "practice",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Практическое применение",
    contextInLesson: "Curriculum как инструмент стабильного обучения",
    contextInHub: "Curriculum learning на практике (Урок 3.3)",
  },

  // ── Урок 3.4: GAIL ──
  {
    lessonId: "3-4",
    lessonPath: "/courses/3-4",
    lessonTitle: "Имитационное обучение (GAIL)",
    lessonLevel: 3,
    hubPath: "/advanced",
    hubTitle: "Продвинутые темы",
    sectionTitle: "Imitation Learning",
    contextInLesson: "GAIL и Behavioral Cloning для обучения из демонстраций",
    contextInHub: "Имитационное обучение из Урока 3.4",
  },
  {
    lessonId: "3-4",
    lessonPath: "/courses/3-4",
    lessonTitle: "Имитационное обучение (GAIL)",
    lessonLevel: 3,
    hubPath: "/unity-ml-agents",
    hubAnchor: "training",
    hubTitle: "Unity ML-Agents",
    sectionTitle: "Обучение агентов",
    contextInLesson: "Запись и использование демонстраций в ML-Agents",
    contextInHub: "Демонстрации для GAIL (Урок 3.4)",
  },
  {
    lessonId: "3-4",
    lessonPath: "/courses/3-4",
    lessonTitle: "Имитационное обучение (GAIL)",
    lessonLevel: 3,
    hubPath: "/math-rl/module-4",
    hubTitle: "Математика RL — Оптимизация",
    sectionTitle: "Adversarial оптимизация",
    contextInLesson: "GAN-подобная оптимизация в GAIL",
    contextInHub: "Adversarial training в контексте GAIL (Урок 3.4)",
  },
  {
    lessonId: "3-4",
    lessonPath: "/courses/3-4",
    lessonTitle: "Имитационное обучение (GAIL)",
    lessonLevel: 3,
    hubPath: "/deep-rl",
    hubAnchor: "algorithms",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Ключевые алгоритмы",
    contextInLesson: "GAIL в семействе Deep RL методов",
    contextInHub: "Imitation Learning как Deep RL метод (Урок 3.4)",
  },

  // ── Урок 3.5: Деплой ONNX ──
  {
    lessonId: "3-5",
    lessonPath: "/courses/3-5",
    lessonTitle: "Деплой модели: ONNX",
    lessonLevel: 3,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "saving",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Сохранение моделей",
    contextInLesson: "Экспорт PyTorch → ONNX формат",
    contextInHub: "Конвертация в ONNX из Урока 3.5",
  },
  {
    lessonId: "3-5",
    lessonPath: "/courses/3-5",
    lessonTitle: "Деплой модели: ONNX",
    lessonLevel: 3,
    hubPath: "/unity-ml-agents",
    hubAnchor: "installation",
    hubTitle: "Unity ML-Agents",
    sectionTitle: "Установка ML-Agents",
    contextInLesson: "Интеграция ONNX-модели в Unity через Sentis",
    contextInHub: "ONNX → Sentis пайплайн (Урок 3.5)",
  },
  {
    lessonId: "3-5",
    lessonPath: "/courses/3-5",
    lessonTitle: "Деплой модели: ONNX",
    lessonLevel: 3,
    hubPath: "/deep-rl",
    hubAnchor: "practice",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Практическое применение",
    contextInLesson: "Деплой обученной модели в продакшен",
    contextInHub: "Деплой Deep RL модели (Урок 3.5)",
  },

  // ── Урок 3.6: Оптимизация гиперпараметров ──
  {
    lessonId: "3-6",
    lessonPath: "/courses/3-6",
    lessonTitle: "Оптимизация гиперпараметров",
    lessonLevel: 3,
    hubPath: "/math-rl/module-4",
    hubTitle: "Математика RL — Оптимизация",
    sectionTitle: "Градиентная оптимизация",
    contextInLesson: "Математика поиска гиперпараметров",
    contextInHub: "Оптимизация гиперпараметров (Урок 3.6)",
  },
  {
    lessonId: "3-6",
    lessonPath: "/courses/3-6",
    lessonTitle: "Оптимизация гиперпараметров",
    lessonLevel: 3,
    hubPath: "/algorithms/ppo",
    hubTitle: "PPO — Proximal Policy Optimization",
    sectionTitle: "Гиперпараметры PPO",
    contextInLesson: "lr, clip_range, n_epochs — настройка PPO",
    contextInHub: "Тюнинг PPO гиперпараметров (Урок 3.6)",
  },
  {
    lessonId: "3-6",
    lessonPath: "/courses/3-6",
    lessonTitle: "Оптимизация гиперпараметров",
    lessonLevel: 3,
    hubPath: "/deep-rl",
    hubAnchor: "practice",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Практическое применение",
    contextInLesson: "Гиперпараметры в Deep RL vs supervised learning",
    contextInHub: "Специфика тюнинга в RL (Урок 3.6)",
  },
  {
    lessonId: "3-6",
    lessonPath: "/courses/3-6",
    lessonTitle: "Оптимизация гиперпараметров",
    lessonLevel: 3,
    hubPath: "/fca-rl",
    hubAnchor: "fca-hyperparams",
    hubTitle: "FCA + RL",
    sectionTitle: "FCA для анализа гиперпараметров",
    contextInLesson: "Анализ экспериментов через формальные понятия",
    contextInHub: "FCA-анализ гиперпараметров из Урока 3.6",
  },

  // ── Урок 3.7: Архитектуры нейросетей ──
  {
    lessonId: "3-7",
    lessonPath: "/courses/3-7",
    lessonTitle: "Архитектуры нейросетей",
    lessonLevel: 3,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "nn",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Нейронные сети (torch.nn)",
    contextInLesson: "CNN, LSTM, Attention — реализация в PyTorch",
    contextInHub: "Архитектуры нейросетей из Урока 3.7",
  },
  {
    lessonId: "3-7",
    lessonPath: "/courses/3-7",
    lessonTitle: "Архитектуры нейросетей",
    lessonLevel: 3,
    hubPath: "/math-rl/module-2",
    hubTitle: "Математика RL — Линейная алгебра",
    sectionTitle: "Линейная алгебра для нейросетей",
    contextInLesson: "Матричные операции в свёрточных и рекуррентных сетях",
    contextInHub: "Линейная алгебра за архитектурами (Урок 3.7)",
  },
  {
    lessonId: "3-7",
    lessonPath: "/courses/3-7",
    lessonTitle: "Архитектуры нейросетей",
    lessonLevel: 3,
    hubPath: "/deep-rl",
    hubAnchor: "foundations",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Основы Deep RL",
    contextInLesson: "Выбор архитектуры под тип наблюдений",
    contextInHub: "Архитектурные решения в Deep RL (Урок 3.7)",
  },
  {
    lessonId: "3-7",
    lessonPath: "/courses/3-7",
    lessonTitle: "Архитектуры нейросетей",
    lessonLevel: 3,
    hubPath: "/fca-rl",
    hubAnchor: "fca-architecture",
    hubTitle: "FCA + RL",
    sectionTitle: "FCA для проектирования архитектуры",
    contextInLesson: "FCA для выбора архитектуры по свойствам задачи",
    contextInHub: "FCA-анализ архитектур из Урока 3.7",
  },
  {
    lessonId: "3-7",
    lessonPath: "/courses/3-7",
    lessonTitle: "Архитектуры нейросетей",
    lessonLevel: 3,
    hubPath: "/fca-rl",
    hubAnchor: "fca-basics",
    hubTitle: "FCA + RL",
    sectionTitle: "Основы FCA",
    contextInLesson: "Формальные понятия для классификации архитектур",
    contextInHub: "Основы FCA, применяемые в Уроке 3.7",
  },

  // ── Финальный проект: Игра с NPC ──
  {
    lessonId: "final-project",
    lessonPath: "/courses/final-project",
    lessonTitle: "Финальный проект: Игра с NPC",
    lessonLevel: 3,
    hubPath: "/unity-projects",
    hubTitle: "Проекты Unity",
    sectionTitle: "Все Unity-проекты",
    contextInLesson: "Финальный проект — объединение всех навыков",
    contextInHub: "Итоговый проект курса (Финальный проект)",
  },
  {
    lessonId: "final-project",
    lessonPath: "/courses/final-project",
    lessonTitle: "Финальный проект: Игра с NPC",
    lessonLevel: 3,
    hubPath: "/algorithms/ppo",
    hubTitle: "PPO — Proximal Policy Optimization",
    sectionTitle: "PPO для NPC",
    contextInLesson: "PPO как основной алгоритм для игрового NPC",
    contextInHub: "PPO в финальном проекте курса",
  },
  {
    lessonId: "final-project",
    lessonPath: "/courses/final-project",
    lessonTitle: "Финальный проект: Игра с NPC",
    lessonLevel: 3,
    hubPath: "/pytorch/cheatsheet",
    hubAnchor: "saving",
    hubTitle: "PyTorch Шпаргалка",
    sectionTitle: "Сохранение моделей",
    contextInLesson: "Экспорт финальной модели для деплоя",
    contextInHub: "Сохранение и деплой модели (Финальный проект)",
  },
  {
    lessonId: "final-project",
    lessonPath: "/courses/final-project",
    lessonTitle: "Финальный проект: Игра с NPC",
    lessonLevel: 3,
    hubPath: "/deep-rl",
    hubAnchor: "practice",
    hubTitle: "Deep Reinforcement Learning",
    sectionTitle: "Практическое применение",
    contextInLesson: "Применение Deep RL в реальной игре",
    contextInHub: "Итоговое применение Deep RL (Финальный проект)",
  },
  {
    lessonId: "final-project",
    lessonPath: "/courses/final-project",
    lessonTitle: "Финальный проект: Игра с NPC",
    lessonLevel: 3,
    hubPath: "/fca-rl",
    hubAnchor: "fca-practice",
    hubTitle: "FCA + RL",
    sectionTitle: "Практика: FCA + PPO",
    contextInLesson: "FCA-анализ обученного NPC-агента",
    contextInHub: "Практический FCA-анализ в Финальном проекте",
  },
];

/** Get all crosslinks for a specific lesson */
export function getLinksForLesson(lessonId: string): CrossLink[] {
  return CROSSLINKS.filter((link) => link.lessonId === lessonId);
}

/** Get all crosslinks pointing to a specific hub (optionally filtered by anchor) */
export function getLinksForHub(hubPath: string, anchor?: string): CrossLink[] {
  return CROSSLINKS.filter((link) => {
    if (link.hubPath !== hubPath) return false;
    if (anchor !== undefined && link.hubAnchor !== anchor) return false;
    return true;
  });
}

/** Check if a lesson level is free (level 1) */
export function isLessonFree(lessonLevel: number): boolean {
  return lessonLevel === 1;
}
