// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjzlsciqgrycqcjhrcpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqemxzY2lxZ3J5Y3FjamhyY3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyOTQ5MTAsImV4cCI6MjA4ODg3MDkxMH0.i5UHTrhV2FoPFAIYq1Y0A-YotWi69HCGH1AWP5Mso1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});